class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'dl2'
        self.UnzipMirrorCommand = 'unzip2'
        self.TarMirrorCommand = 'tar2'
        self.ZipMirrorCommand = 'zip2'
        self.CancelMirror = 'batal2'
        self.CancelAllCommand = 'batalin2'
        self.ListCommand = 'cari2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users2'
        self.AuthorizeCommand = 'auth2'
        self.UnAuthorizeCommand = 'unauth2'
        self.AddSudoCommand = 'addsudo2'
        self.RmSudoCommand = 'rmsudo2'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stat2'
        self.HelpCommand = 'bantuan2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'salin2'
        self.CountCommand = 'hitung2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.ConfigMenuCommand = 'config2'
        self.ShellCommand = 'shell2'
        self.UpdateCommand = 'update2'
        self.ExecHelpCommand = 'exechelp2'
        self.TsHelpCommand = 'tshelp2'

BotCommands = _BotCommands()
